### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yuler** [yuler/mp-api#1]
- [x] #3
- [x] #4
---
- [ ] Deploy Server
- [ ] Move to monorepo
- [ ] Draw simple flowcharts
- [ ] Write some test cases
